#!/bin/sh
#
# /etc/init.d/rcS - run once at boot time

CFG_DIR="/mnt/lg/user/lgmod"
S_SH="$CFG_DIR/auto_stop.sh"

run_scripts() {
	for i in /etc/rc.d/$1*; do
		[ -x $i ] && $i $2 2>&1
	done
}



case "$1" in
	boot)
#		run_scripts S start
		.  /etc/rc.d/rc.sysinit
		(/etc/lgmod.sh)&
		. /etc/rc.d/rc.local
		
		;;
	shutdown)
		run_scripts K stop
		exec /bin/sh $S_SH
		/bin/umount -a -r
		;;
		
	*)
		echo "Usage: $0 {boot|shutdown}"
		exit 1
esac

exit 0
